### ISSUE TITLE
Increase legibility of text on Header images

### ISSUE THREAD

**Issue by jpasholk** [jpasholk/jekyll-uikit#26]

**Comment by jpasholk** [comment]
Play around with the [filter](https://css-tricks.com/almanac/properties/f/filter/) CSS property and see if this can be improved. 

Maybe with opacity?

**Comment by daviddarnes** [comment]
I'd probably go with a half transparency on the header image and let a much darker colour come through. So that no matter how light the image was the text would always be readable. That or just make sure the default image provided in the theme has enough contrast, you can't cater for every edge-case and this is one of those. The theme user should be able to set an image that compliments the header text colour

**Comment by jpasholk** [comment]
Right on, thanks David! I’ll play around with it.

Maybe something like ```opacity: 0.5;```?
